#!/bin/sh
#---help---
# Usage: $PROGNAME [options]
#
# Suspend or hibernate the system.
#
# Options:
#   -n   Dry run (sleep for 5s instead of suspend/hibernate)
#   -S   Low-power idle (ACPI S1)
#   -z   Suspend to RAM (ACPI S3) [default for zzz(8)]
#   -Z   Hibernate to disk & power off (ACPI S4) [default for ZZZ(8)]
#   -R   Hibernate to disk & reboot
#   -H   Hibernate to disk & suspend (aka suspend-hybrid)
#   -V   Print program name & version and exit.
#   -h   Show this message and exit.
#
# Homepage: https://github.com/jirutka/zzz
#---help---
set -eu

readonly PROGNAME=${0##*/}
readonly VERSION='0.0.0'
readonly HOOKS_DIR='/etc/zzz.d'


help() {
	tag='#---help---'
	sed -n "/^$tag/,/^$tag/{/^$tag/d; s/^# \\?//; s/\$PROGNAME/$PROGNAME/; p}" "$0"
}

log() {
	logger -p "user.$1" -t zzz -s "$2"
}

die() {
	log err "$*"
	exit 10
}

run_hooks() {
	local stage=$1
	local rc=0

	[ -d "$HOOKS_DIR" ] || return 0

	# Only for compatibility with Void Linux.
	local stagedir='suspend'
	[ "$stage" = 'post' ] && stagedir='resume'

	local f; for f in "$HOOKS_DIR"/$stagedir/* "$HOOKS_DIR"/*; do
		[ -f "$f" ] && [ -x "$f" ] || continue

		$f "$stage" "$ZZZ_MODE" || {
			log warn "hook script ${f#$HOOKS_DIR/} exited with code $?"
			rc=11
		}
	done

	return $rc
}


ZZZ_MODE=suspend
[ "$PROGNAME" = 'ZZZ' ] && ZZZ_MODE=hibernate
ZZZ_HIBERNATE_MODE=platform

while getopts ':HnRSzZVh' OPT; do
	case "$OPT" in
		H) ZZZ_MODE=hibernate; ZZZ_HIBERNATE_MODE=suspend;;
		n) ZZZ_MODE=noop;;
		R) ZZZ_MODE=hibernate; ZZZ_HIBERNATE_MODE=reboot;;
		S) ZZZ_MODE=standby;;
		z) ZZZ_MODE=suspend;;
		Z) ZZZ_MODE=hibernate;;
		V) echo "$PROGNAME $VERSION"; exit 0;;
		h) help; exit 0;;
		\?) echo "$PROGNAME: unknown option: -$OPTARG" >&2; exit 1;;
	esac
done

export ZZZ_MODE ZZZ_HIBERNATE_MODE

case "$ZZZ_MODE" in
	suspend) grep -q mem /sys/power/state || die 'suspend is not supported';;
	hibernate) grep -q disk /sys/power/state || die 'hibernate is not supported';;
esac

[ -w /sys/power/state ] || die '/sys/power/state is not writable'

(
	rc=0
	flock -n 9 || die 'another instance of zzz is running'

	log info "going to $ZZZ_MODE"
	run_hooks pre || rc=$?

	case "$ZZZ_MODE" in
		hibernate)
			echo "$ZZZ_HIBERNATE_MODE" >/sys/power/disk
			printf disk >/sys/power/state || die 'hibernate died';;
		standby) printf freeze >/sys/power/state || die 'standby died';;
		suspend) printf mem >/sys/power/state || die 'suspend died';;
		noop) sleep 5;;
	esac

	log info "resuming from $ZZZ_MODE"
	run_hooks post || rc=$?

	exit $rc
) 9</sys/power
